### PR TITLE
Re-enable disabled code for 5.9 transition

### LINKED ISSUE #624: [xenial] Can't scroll to the bottom of the home screen
- Device: FP2
- Channel: 16.04/devel
- Build: r301

### Steps to reproduce
Scroll down on the home screen. (Does not happen every time. Not sure what triggers this)

### Expected behavior
I can scroll until I reach the bottom.

### Actual behavior
I can scroll like 80% of the app list. The last position is not even at the end of a row. I can try to scroll further, but the rest of the apps is not there and it bounces back when releasing the finger. Therefore, I cannot start some Apps, like the clock ("Uhr" in German).

### Logfiles and additional information
Restarting the phone fixes this temporarily.
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2031135/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2031136/UTlogcat.txt)

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
This fixes https://github.com/ubports/ubuntu-touch/issues/624 by correctly overriding QQuickGeometryChange. It also fixes the tests that were disabled when upgrading to 5.9.

I abused CI with this one, please squash and merge

### CODE REVIEW

File: tests/plugins/Ubuntu/Gestures/GestureTest.cpp [hunk 1]
```diff
@@ -105,9 +105,6 @@ void GestureTest::sendTouch(qint64 timestamp, int id, QPointF pos,
 
     QTouchEvent touchEvent(eventType, m_device, Qt::NoModifier, Qt::TouchPointPressed, points);
     QCoreApplication::sendEvent(m_view, &touchEvent);
-
-    QQuickWindowPrivate *windowPrivate = QQuickWindowPrivate::get(m_view);
-    windowPrivate->flushDelayedTouchEvent();
```
Comment (dpniel) [inline tests/plugins/Ubuntu/Gestures/GestureTest.cpp]: These changes might bring in a race condition where not all events have been delivered before the next comparison which assumes they have.

Looks like the api has changed, but [`flushFrameSynchronousEvents`](https://code.woboq.org/qt5/qtdeclarative/src/quick/items/qquickwindow.cpp.html#_ZN19QQuickWindowPrivate27flushFrameSynchronousEventsEv) should do the same thing and ensure all events have been delivered.

**Review by dpniel — CHANGES_REQUESTED** [review]
Awesome! Just one change needed in the tests as far as I can see.

**Comment by UniversalSuperBox** [comment]
I'm not sure how the remote got work I didn't have in that one, but okay.

All instances of that flush should be fixed now.

**Review by dpniel — APPROVED** [review]
LGTM. :+1:

**Review by mariogrip — APPROVED** [review]
LGTM :+1:
